[profile.default]
src = "contracts"
test = "test-sol"
out = "out"
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "none"
cbor_metadata = false

[fmt]
line_length = 100
